// User Actions
export const SET_USER = "SET_USER";

// THREAD ACTIONS
//  - THREAD - currentThread Actions
export const ADD_MESSAGE = "ADD_MESSAGE";
export const ADD_MESSAGE_STREAM = "ADD_MESSAGE_STREAM";
export const ADD_ASSISTANT_RESPONSE = "SET_ASSISTANT_RESPONSE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const EDIT_MESSAGE = "EDIT_MESSAGE";

//  - THREAD - Threads Actions
export const SET_THREADS = "SET_THREADS";
export const ADD_THREAD = "ADD_THREAD";
export const UPDATE_THREAD_LASTUPDATED = "UPDATE_THREAD_LASTUPDATED";
export const CREATE_NEW_THREAD = "CREATE_NEW_THREAD";
export const SET_CURRENT_THREAD_ID = "SET_CURRENT_THREAD_ID";
export const GET_CURRENT_THREAD = "GET_CURRENT_THREAD";
export const RESET_CURRENT_THREAD = "RESET_CURRENT_THREAD";
export const DELETE_THREAD = "DELETE_THREAD";
export const SET_THREAD_TITLE = "SET_THREAD_TITLE";
export const SET_CURRENT_THREAD_URLS = "SET_CURRENT_THREAD_URLS";

// Mode Actions
export const SET_MODE = "SET_MODE";
export const SET_MODEL = "SET_MODEL";

// Side Panel Actions

// Attachments Modal Actions
export const SHOW_ATTACHMENT_MODAL = "SHOW_ATTACHMENT_MODAL";
export const HIDE_ATTACHMENT_MODAL = "HIDE_ATTACHMENT_MODAL";
